# Your project's server will run on proxy
PROXY: "http://local.yiiframework.com"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist"
  # Path to source folder
  src: "assets/src"
  # Paths to fonts
  npmfonts:
    - "node_modules/typeface-pt-sans/files/*"
    - "node_modules/typeface-fira-mono/files/*"
  fonts:
    - "vendor/bower-asset/font-awesome/fonts/**/*"
    - "vendor/bower-asset/bootstrap/fonts/**/*"
    - "assets/src/fonts/ptsans-bold/**/*"
    - "assets/src/fonts/ptsans-regular/**/*"
    - "assets/src/fonts/fira-mono/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules"
    - "vendor/bower-asset/glidejs/src/sass"
    - "vendor/bower-asset/bootstrap-social"
    - "vendor/scrivo/highlight.php"
    - "vendor/bower-asset/font-awesome/scss"
    - "vendor/bower-asset/sass-rem"
    - "vendor/bower-asset/codemirror/lib"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    - "node_modules/jquery/dist/jquery.js"
    - "node_modules/bootstrap/js/dist/util.js"
    - "node_modules/bootstrap/js/dist/collapse.js"
    - "node_modules/bootstrap/js/dist/dropdown.js"
    - "vendor/bower-asset/scrollup/dist/jquery.scrollUp.js"
    - "vendor/yiisoft/yii2/assets/yii.js"
    - "vendor/yiisoft/yii2/assets/yii.validation.js"
    - "vendor/yiisoft/yii2/assets/yii.activeForm.js"
    - "vendor/yiisoft/yii2-authclient/src/assets/authchoice.js"
    - "vendor/bower-asset/glidejs/dist/glide.js"
    - "assets/src/js/polyfill.js"
    - "assets/src/js/custom.js"
    - "assets/src/js/search.js"
    - "assets/src/js/voting.js"
    - "assets/src/js/star.js"
    # codemirror editor
    - "vendor/bower-asset/codemirror/lib/codemirror.js"
    - "vendor/bower-asset/codemirror/mode/shell/shell.js"
    - "vendor/bower-asset/codemirror/mode/clike/clike.js"
    - "vendor/bower-asset/codemirror/mode/css/css.js"
    - "vendor/bower-asset/codemirror/mode/javascript/javascript.js"
    - "vendor/bower-asset/codemirror/mode/php/php.js"
    - "vendor/bower-asset/codemirror/mode/sass/sass.js"
    - "vendor/bower-asset/codemirror/mode/sql/sql.js"
    - "vendor/bower-asset/codemirror/mode/twig/twig.js"
    - "vendor/bower-asset/codemirror/mode/xml/xml.js"
    - "vendor/bower-asset/codemirror/mode/yaml/yaml.js"
    - "vendor/bower-asset/codemirror/mode/htmlmixed/htmlmixed.js"
    - "vendor/bower-asset/codemirror/mode/meta.js"
    - "vendor/bower-asset/codemirror/mode/markdown/markdown.js"
    - "vendor/bower-asset/codemirror/addon/mode/overlay.js"
    - "vendor/bower-asset/codemirror/mode/gfm/gfm.js"
    - "vendor/bower-asset/codemirror/addon/edit/continuelist.js"
    - "vendor/bower-asset/codemirror/addon/fold/xml-fold.js"
    - "vendor/bower-asset/codemirror/addon/edit/matchbrackets.js"
    - "vendor/bower-asset/codemirror/addon/edit/closebrackets.js"
    - "vendor/bower-asset/codemirror/addon/edit/closetag.js"
    - "vendor/bower-asset/codemirror/addon/display/panel.js"
    - "vendor/bower-asset/codemirror-buttons/buttons.js"
    - "assets/src/js/editor.js"
    # jquery.fileupload plugin
    - "vendor/bower-asset/jquery-ui/ui/widget.js"
    - "vendor/bower-asset/blueimp-file-upload/js/jquery.fileupload.js"
    - "assets/src/js/upload.js"
